### ISSUE TITLE
Get an error when click the 3 sample prompts in the frontend

### ISSUE THREAD

**Issue by NanaXiong00** [Azure-Samples/azure-search-openai-javascript#117]
**Describe the issue:**
Get an error when click the 3 sample prompts in the frontend. Failed to run locally with the following error.
![image](https://github.com/Azure-Samples/azure-search-openai-javascript/assets/138103031/c98b9464-39ac-4141-b9dd-a3372257a59c)

**Environment:**
- Readme - local

**Repro Steps:**
1. Run `azd auth login`
2. Run `azd init -t azure-search-openai-javascript` 
3. Run `azd up`
4. Run `azd env get-values > .env`
5. Run `npm start`
6. Open the web: http://127.0.0.1:5173/
7. Click the 3 sample prompts

**Expected behavior**
Open the web page and chat successfully.

@charris-msft for notification.

**Comment by anfibiacreativa** [comment]
@NanaXiong00 @charris-msft Please provide more information like an error log. Not running when there are env vars issues is expected behavior.

**Comment by shibbas** [comment]
@anfibiacreativa - looks like there is a step missing. After `azd env get-values > .env` you need to run `az login` before doing npm start or the calls fail due to identity issues.

**Comment by anfibiacreativa** [comment]
Thank you for finding the fix @shibbas !

**Comment by NanaXiong00** [comment]
> @NanaXiong00 @charris-msft Please provide more information like an error log. Not running when there are env vars issues is expected behavior.

@anfibiacreativa We tried to run `az login` after `azd env get-values > .env` and before `npm start`, but this issue still exists. Here's the error log when run `npm start`:
<img width="800" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-javascript/assets/138103031/489e07cb-69cf-4ee3-bcc9-4f0b5dfb8cea">
<img width="800" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-javascript/assets/138103031/aa3bff54-c39e-4016-af2f-d953deee95d0">
<img width="800" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-javascript/assets/138103031/2161fc43-a9b9-458c-ab84-bdc140843cba">

**Comment by sinedied** [comment]
Could you try updating to the latest version and running "npm ci" again
before redeployment?

The auth error may be linked to an issue with the @azure/identity SDK that
was fixed yesterday.

Le ven. 10 nov. 2023, 18:54, Natalia Venditto ***@***.***> a
écrit :

**Comment by NanaXiong00** [comment]
> Could you try updating to the latest version and running "npm ci" again before redeployment? The auth error may be linked to an issue with the @azure/identity SDK that was fixed yesterday. Le ven. 10 nov. 2023, 18:54, Natalia Venditto ***@***.***> a écrit :

@sinedied, We are testing locally with the latest code, running `azd up` failed, error details are in https://github.com/Azure-Samples/azure-search-openai-javascript/issues/120#issuecomment-1807589411. After this `azd up` issue fixed, we will continue testing the next steps.

**Comment by NanaXiong00** [comment]
@sinedied - Based on the latest code, this issue can still be reproduced.
After investigation, we found that the log shows that the `SEARCH_API_URI` parameters cannot be obtained in `.env` when running `npm start` locally. After add the following code in `./packages/webapp/vite.config.ts`, the test result is pass, able to click the 3 sample prompts in the frontend normally. What do you think?
```
import dotenv from "dotenv";
dotenv.config({ path: '../../.env' })
```


<img width="700" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-javascript/assets/138103031/e8332ac6-a887-42cd-adae-efd119bd3eee">

**Comment by sinedied** [comment]
@NanaXiong00 that's expected. When running locally, `SEARCH_API_URI` is not set and cause the webapp to fall back to `localhost:3000` for the API, using the reverse proxy set at the bottom of vite.config.ts.

To run the app locally you need to also run the search API, either manually with `npm run dev --workspace=search-api` or simply by running `npm start` at the root of the repo, which will run all services locally.

**Comment by charris-msft** [comment]
@dfberry - Does the doc reflect the requirements from @sinedied's comment above?

**Comment by v-jiaodi** [comment]
> @anfibiacreativa - looks like there is a step missing. After `azd env get-values > .env` you need to run `az login` before doing npm start or the calls fail due to identity issues.

@sinedied @charris-msft 
This issue is due to environment variable containing the value of `Azure Service Principal`. When using `Default AzureCredential`, it prioritize the use of `EnvironmentCredential`. Granting permissions to `Azure Service Principal` or removing `Azure Service Principal` from the environment variable to ensure normal access.

Regarding the issue of identity, I suggest adding troubleshooting for it.

In addition, in the `Windows` environment, after resolving the permission issue, encountered the following issue:

![image](https://github.com/Azure-Samples/azure-search-openai-javascript/assets/80496810/316b17e6-7816-4393-887a-273aafd80017)

By reviewing the logs, we found that there were some error logs during the execution of `azd up`, which resulted in `gptkbindex` not being created.
![image](https://github.com/Azure-Samples/azure-search-openai-javascript/assets/80496810/2a3cf103-291e-4807-93c1-a7b412f846bc)

This is because the installation path of `nodejs` cannot be read normally. For `Windows` environment, `nodejs` is installed in the folder `Program Files` by default. This folder name contains spaces, which causes a reading error.

Please help solve the issues mentioned above.

**Comment by sinedied** [comment]
@v-jiaodi Thanks for the detailed feedbacks!

Regarding the `az login` issue, this is tracked here: https://github.com/Azure/azure-dev/issues/2975 as `azd` should authenticate you also with the `az cli`

For the `Service Principal` issue, this is expected behavior from `azd` CLI. The fact that it doesn't work as expected is probably due to the issue above with not being logged into `az` CLI.

For the last one with the Node.js path issue, could you create a separate issue for it so we can track it properly? I already have the fix for this one, but it would be better to be in its own issues for other folks bumping into it.

Thanks!

**Comment by v-jiaodi** [comment]
> For the `Service Principal` issue, this is expected behavior from `azd` CLI. The fact that it doesn't work as expected is probably due to the issue above with not being logged into `az` CLI.
> 
@sinedied You may have misunderstood my meaning. During our testing process, if the environment variables include `AZURE_TENANT_ID`, `AZURE_CLIENT_ID`, and `AZURE_CLIENT_SECRET`. Although running `az login`, for `Default AzureCredential`, priority is given to using `EnvironmentCredential` over `AzureCliCredential`. For more details, please refer to [Azure identity SDK ](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/identity/identity/README.md#defaultazurecredential).

That's precisely why NanaXiong00 went wrong, so I suggest adding troubleshooting for it in README.


For the Node.js path issue, I have created a issue for it:  https://github.com/Azure-Samples/azure-search-openai-javascript/issues/141

**Comment by v-jiaodi** [comment]
Adding troubleshooting like this：
You're getting "401 Principal does not have access to API/Operation" during running locally. That's likely because your environment variables include `AZURE_TENANT_ID`, `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET`, Granting permissions to `Service Principal` or removing `Service Principal` from your environment variable. For more details, please refer to [Azure identity SDK](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/identity/identity/README.md#defaultazurecredential).
